parameters:
    # PHP version checker
    php_version_checker_allowed_php_versions: ['7.4', '8.0']
    php_version_checker_sdk_versions: ['7.4', '8.0']
    php_version_checker_doc_url: https://docs.spryker.com/docs/scos/dev/keeping-a-project-upgradable/upgradability-guidelines/php-version.html

    evaluator_dir: '%kernel.project_dir%'
    # Dead code checker
    dead_code_checker_doc_url: https://docs.spryker.com/docs/scos/dev/keeping-a-project-upgradable/upgradability-guidelines/dead-code-checker.html

    # Security checker
    security_checker_doc_url: https://docs.spryker.com/docs/scos/dev/keeping-a-project-upgradable/upgradability-guidelines/security.html

    # Multidimensional array checker
    multidimensional_array_checker_doc_url: https://docs.spryker.com/docs/scos/dev/keeping-a-project-upgradable/upgradability-guidelines/multidimensional-array.html

    # Dependency provider additional logic checker
    dp_additional_logic_checker_doc_url: https://docs.spryker.com/docs/scos/dev/keeping-a-project-upgradable/upgradability-guidelines/dependency-provider-contains-addition-logic.html

    # Plugin registration with restriction checker
    plugin_registration_checker_doc_url: https://docs.spryker.com/docs/scos/dev/keeping-a-project-upgradable/upgradability-guidelines/plugin-registration-with-restrintions.html

    # Single plugin argument checker
    single_plugin_argument_checker_doc_url: https://docs.spryker.com/docs/scos/dev/keeping-a-project-upgradable/upgradability-guidelines/single-plugin-argument.html

    # Minimum allowed shop version
    minimum_allowed_shop_version_checker_doc_url: https://docs.spryker.com/docs/scos/dev/keeping-a-project-upgradable/upgradability-guidelines/minimum-allowed-shop-version.html
    minimum_allowed_shop_version_checker_version: '202204.0'
    minimum_allowed_shop_version_checker_file: '%evaluator_dir%/data/minimum-allowed-package-versions.json'
